version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: activepieces
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: activepieces
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ap-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data

  activepieces:
    image: activepieces/activepieces:latest
    container_name: activepieces
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8990:80"
    environment:
      AP_ENVIRONMENT: prod
      AP_FRONTEND_URL: http://localhost:8990
      AP_REDIS_HOST: redis
      AP_REDIS_PORT: 6379
      AP_POSTGRES_HOST: postgres
      AP_POSTGRES_PORT: 5432
      AP_POSTGRES_USERNAME: activepieces
      AP_POSTGRES_PASSWORD: strongpassword
      AP_POSTGRES_DATABASE: activepieces
      AP_ENCRYPTION_KEY: 057c4a29a238438a695d4a06751db849
      AP_JWT_SECRET: 064c8b2d7910637cbf0d1f2d9605c729

    volumes:
      - ap-data:/app/data

volumes:
  postgres-data:
  redis-data:
  ap-data:
